    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Customer;

import business.EcoSystem;
import business.airline.Airplane;
import business.airport.Airport;
import business.customer.Customer;
import business.employee.AirlineEmployee;
import business.util.Constant;
import business.util.Utils;
import java.awt.Graphics;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhetr
 */
public class BookTicketPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookTicketPanel
     */
    private EcoSystem ecoSystem;
    private Customer customer;
    private JFrame mainJFrame;
    DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
    public BookTicketPanel(EcoSystem ecoSystem, Customer customer, JFrame mainJFrame) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.customer = customer;
        this.mainJFrame = mainJFrame;
        
        List<Airport> airports = ecoSystem.getAirportDirectory().getAirports();
        for(Airport airport : airports)
        {
            comboBoxDeparture.addItem(airport.getAirportName());
            comboBoxArrival.addItem(airport.getAirportName());
        }
    }
    
    @Override
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        ImageIcon img = new ImageIcon("src/Images/sky.jpeg");
        g.drawImage(img.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();
        bBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxDeparture = new javax.swing.JComboBox<>();
        comboBoxArrival = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 153, 255));
        setForeground(new java.awt.Color(153, 153, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("BOOK YOUR FLIGHT");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBack2.setBackground(new java.awt.Color(255, 255, 255));
        btnBack2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(0, 102, 255));
        btnBack2.setText("<< Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        bBook.setBackground(new java.awt.Color(255, 255, 255));
        bBook.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bBook.setForeground(new java.awt.Color(0, 102, 204));
        bBook.setText("Book");
        bBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBookActionPerformed(evt);
            }
        });

        tblResult.setBackground(new java.awt.Color(204, 255, 255));
        tblResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Airline", "Flight No", "Time", "Price", "Duration", "Seats Avaliable"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Date:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("To:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("From:");

        comboBoxDeparture.setForeground(new java.awt.Color(0, 102, 204));
        comboBoxDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDepartureActionPerformed(evt);
            }
        });

        comboBoxArrival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxArrivalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(comboBoxDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(bBook, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(543, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboBoxDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboBoxArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(123, 123, 123)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bBook, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxDepartureActionPerformed

    private void bBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBookActionPerformed
        int selectedRow = tblResult.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to book flight", "Error", ERROR_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblResult.getModel();
        Airplane airplane = (Airplane) model.getValueAt(selectedRow, 1);
        SelectSeat selectSeat = new SelectSeat(ecoSystem, customer, airplane, df.format(txtDate.getDate()), "2", mainJFrame);
        Utils.newPage(selectSeat);
    }//GEN-LAST:event_bBookActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        CustomerPanel customerPanel = new CustomerPanel(ecoSystem, customer, mainJFrame);
        Utils.previosPage(customerPanel);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String departureAirport = (String) comboBoxDeparture.getSelectedItem();
        String arrivalAirport = (String) comboBoxArrival.getSelectedItem();
        
        String date = df.format(txtDate.getDate());
//        Integer noOfTraveller = Integer.valueOf((String) comboBoxNoOfTraveller.getSelectedItem());
        if(departureAirport.equals(arrivalAirport))
        {
            showMessageDialog(this, "Departure and Arrival airport cannot be same", "Error", ERROR_MESSAGE);
            return;
        }
        
        
        Airport departure = ecoSystem.getAirportDirectory().getAirportFromName(departureAirport);
        Airport arrival = ecoSystem.getAirportDirectory().getAirportFromName(arrivalAirport);
        List<Airplane> result = new ArrayList();
        for(Airplane airplane : ecoSystem.getAirplaneDirectory().getAirplanes())
        {
            if(airplane.getDepartureAirport().equals(departure) 
                    && airplane.getArrivalAirport().equals(arrival) 
                    && (airplane.getBooking().get(date) == null || airplane.getBooking().get(date).size() < Constant.noOfSeats  ))
            {
                result.add(airplane);
            }
        }
        populateTable(result);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxArrivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxArrivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxArrivalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBook;
    private javax.swing.JButton btnBack2;
    private javax.swing.JComboBox<String> comboBoxArrival;
    private javax.swing.JComboBox<String> comboBoxDeparture;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResult;
    private com.toedter.calendar.JDateChooser txtDate;
    // End of variables declaration//GEN-END:variables

    private void populateTable(List<Airplane> airplanes) {
        DefaultTableModel model = (DefaultTableModel) tblResult.getModel();
        model.setRowCount(0);
        String date = df.format(txtDate.getDate());

        for(Airplane airplane : airplanes)
        {
            Object[] row = new Object[7];
            row[0] = airplane.getAirline();
            row[1] = airplane;
            row[2] = airplane.getDepartureTime();
            row[3] = airplane.getPrice();
            row[4] = airplane.getTotalHours();
            row[5] = Constant.noOfSeats;
            if(airplane.getBooking().get(date) != null)
            {
                row[5] = Constant.noOfSeats - airplane.getBooking().get(date).size();
            }
            model.addRow(row);
        }
    }
}
