/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Airline;

import business.DB40Util.DB4OUtil;
import business.EcoSystem;
import business.airline.Airline;
import business.util.Utils;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import ui.HomePage;

/**
 *
 * @author ashis
 */
public class AirlinePanel extends javax.swing.JPanel {

    /**
     * Creates new form AirlinePanel
     */
    EcoSystem ecoSystem;
    Airline airline;
    JFrame mainJFrame;
    public AirlinePanel(EcoSystem ecoSystem, Airline airline, JFrame mainJFrame) {
        initComponents();
        this.ecoSystem = ecoSystem;
        this.airline = airline;
        this.mainJFrame = mainJFrame;
//        jPanel1.setOpaque(false);
    }
    
     @Override
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);
        ImageIcon img = new ImageIcon("src/Images/airplane-wing.jpeg");
        //g.drawImage(img.getImage(), 0, 0, 700, 800, null);
     
        g.drawImage(img.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_bookingHistory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_bookTickets = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 204));
        setForeground(new java.awt.Color(204, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_bookingHistory.setBackground(new java.awt.Color(255, 255, 255));
        btn_bookingHistory.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_bookingHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-aircraft (1).gif"))); // NOI18N
        btn_bookingHistory.setText("Flights");
        btn_bookingHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookingHistoryActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Airline Dashboard");
        jLabel1.setMaximumSize(new java.awt.Dimension(102, 100));

        btn_bookTickets.setBackground(new java.awt.Color(255, 255, 255));
        btn_bookTickets.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btn_bookTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-leadership.gif"))); // NOI18N
        btn_bookTickets.setText("Employees");
        btn_bookTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bookTicketsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(258, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_bookingHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bookTickets))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(btn_bookTickets)
                .addGap(265, 265, 265)
                .addComponent(btn_bookingHistory)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_bookTickets, btn_bookingHistory});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DB4OUtil dB4OUtil = DB4OUtil.getInstance();
        dB4OUtil.storeSystem(ecoSystem);
        HomePage newMainJFrame = new HomePage();
        newMainJFrame.setVisible(true);
        mainJFrame.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_bookingHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookingHistoryActionPerformed
        ViewFlight viewFlight = new ViewFlight(mainJFrame, airline, ecoSystem);
        Utils.newPage(viewFlight);
    }//GEN-LAST:event_btn_bookingHistoryActionPerformed

    private void btn_bookTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bookTicketsActionPerformed
//        AddAirlineEmployeePanel addAirineEmployeePanel = new AddAirlineEmployeePanel(mainJFrame, airline, ecoSystem);
//        Utils.newPage(addAirineEmployeePanel);
        
        ViewEmployees viewEmployees = new ViewEmployees(mainJFrame, airline, ecoSystem);
        Utils.newPage(viewEmployees);
    }//GEN-LAST:event_btn_bookTicketsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bookTickets;
    private javax.swing.JButton btn_bookingHistory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
